import Head from 'next/head';
import Hero from '../components/Hero';
import Content from '../components/Content';


export default function Home() {
  return (
    <main>
      <Head>
        <title>Eric's Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Hero heading="Hello World, have a great day." />
      <Content />

    </main>
  )
}
