import Head from 'next/head';
import { useEffect, useRef } from 'react';
import Canvas from '../components/Canvas';
import Hero from '../components/Hero';
import Section from '../components/Section';
import Content from '../components/Content';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/dist/ScrollTrigger';
// import Scroll from '../lib/utils/scroll';

export default function Home() {
  gsap.registerPlugin(ScrollTrigger);
  const content = "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Culpa, voluptatum qui aliquid tempora quasi, similique natus temporibus error optio mollitia cupiditate quaerat eos nemo, minus impedit! Reprehenderit architecto alias, sunt quod voluptatem aliquam dolores odit autem consequuntur, illo et? Expedita eum qui accusamus voluptates. Nemo exercitationem voluptatibus est quos? Eaque.";

  return (
    <main>
      <Head>
        <title>Eric&apos;s Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="scrollable">
        <Canvas />
        <Hero />
        <Section classLabel="content">
          <Content content={content} />
        </Section>
      </div>

    </main>
  )
}
